# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ephr_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllergyServerityMaster',
        ),
        migrations.RemoveField(
            model_name='dpvisits',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='dpvisits',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='dpvisits',
            name='visit_status',
        ),
        migrations.DeleteModel(
            name='DrugMaster',
        ),
        migrations.DeleteModel(
            name='Icd10',
        ),
        migrations.RemoveField(
            model_name='pvallergy',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='pvallergy',
            name='created_doc_id',
        ),
        migrations.RemoveField(
            model_name='pvallergy',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='pvlaborders',
            name='ordered_by',
        ),
        migrations.RemoveField(
            model_name='pvlaborders',
            name='ordered_to',
        ),
        migrations.RemoveField(
            model_name='pvlaborders',
            name='processed_by',
        ),
        migrations.DeleteModel(
            name='PvLabresults',
        ),
        migrations.RemoveField(
            model_name='pvprescription',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pvprescription',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='pvprescription',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='pvprescriptiondetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pvprescriptiondetails',
            name='drug_type',
        ),
        migrations.RemoveField(
            model_name='pvprescriptiondetails',
            name='generic_id',
        ),
        migrations.RemoveField(
            model_name='pvprescriptiondetails',
            name='prescription_id',
        ),
        migrations.RemoveField(
            model_name='pvprescriptiondetails',
            name='strenght_id',
        ),
        migrations.RemoveField(
            model_name='pvproblemlist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pvproblemlist',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='pvproblemlist',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pvradorders',
            name='ordered_by',
        ),
        migrations.RemoveField(
            model_name='pvradorders',
            name='ordered_to',
        ),
        migrations.RemoveField(
            model_name='pvradorders',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='pvradorders',
            name='processed_by',
        ),
        migrations.DeleteModel(
            name='PvRadresults',
        ),
        migrations.RemoveField(
            model_name='pvreminders',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pvreminders',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='AllergyCategoryMaster',
        ),
        migrations.DeleteModel(
            name='DiagnosisStatusMaster',
        ),
        migrations.DeleteModel(
            name='DpUser',
        ),
        migrations.DeleteModel(
            name='DpVisits',
        ),
        migrations.DeleteModel(
            name='DrugTypeMaster',
        ),
        migrations.DeleteModel(
            name='GenericMaster',
        ),
        migrations.DeleteModel(
            name='PhUser',
        ),
        migrations.DeleteModel(
            name='PvAllergy',
        ),
        migrations.DeleteModel(
            name='PvLaborders',
        ),
        migrations.DeleteModel(
            name='PvPrescription',
        ),
        migrations.DeleteModel(
            name='PvPrescriptionDetails',
        ),
        migrations.DeleteModel(
            name='PvProblemlist',
        ),
        migrations.DeleteModel(
            name='PvRadorders',
        ),
        migrations.DeleteModel(
            name='PvReminders',
        ),
        migrations.DeleteModel(
            name='RdUser',
        ),
        migrations.DeleteModel(
            name='StrengthMaster',
        ),
        migrations.DeleteModel(
            name='VisitStatusMaster',
        ),
    ]
