from django.contrib import admin
from .models import *
import cloudinary,cloudinary.uploader
# Register your models here.
# admin.site.register(PvAllergy)
# # admin.site.register(AllergyCategoryMaster)
# # admin.site.register(AllergyServerityMaster)
# admin.site.register(PvProblemlist)
# admin.site.register(Icd10)
# admin.site.register(DiagnosisStatusMaster)
# admin.site.register(DpUser)
# admin.site.register(DpVisits)
# admin.site.register(VisitStatusMaster)
# admin.site.register(PvPrescription)
# admin.site.register(PvPrescriptionDetails)
# admin.site.register(DrugMaster)
# admin.site.register(GenericMaster)
# admin.site.register(StrengthMaster)
# admin.site.register(DrugTypeMaster)
# admin.site.register(PvLaborders)
# admin.site.register(PvLabresults)
# admin.site.register(PvRadorders)
# admin.site.register(PvRadresults)
# admin.site.register(PvReminders)
# admin.site.register(PvUploadedFiles)
# admin.site.register(PhUser)
# admin.site.register(RdUser)